FROM ubuntu:20.04

# 패키지 업데이트 및 Nginx 설치
RUN apt-get update && apt-get install -y nginx && rm -rf /var/lib/apt/lists/*

# Nginx 설정 복사
# COPY default.conf /etc/nginx/conf.d/default.conf



# Nginx 실행
CMD ["nginx", "-g", "daemon off;"]

# Nginx 기본 포트 노출
EXPOSE 80